name: Terraform Deployment

on:
  workflow_dispatch:
     inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - PROD
jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      plan_status: ${{ job.status }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS & Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.environment == 'PROD' && secrets.AWS_ACCESS_KEY_ID_PROD || secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ github.event.inputs.environment == 'PROD' && secrets.AWS_SECRET_ACCESS_KEY_PROD || secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd ${{ github.event.inputs.environment }} && terraform init

      - name: Terraform Plan
        run: cd ${{ github.event.inputs.environment }} && terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

  apply:
    name: Terraform Apply
    needs: plan                      # This makes 'apply' wait for 'plan' to finish
    runs-on: ubuntu-latest
    environment: production          # <--- THIS triggers the approval button
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS & Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.environment == 'PROD' && secrets.AWS_ACCESS_KEY_ID_PROD || secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ github.event.inputs.environment == 'PROD' && secrets.AWS_SECRET_ACCESS_KEY_PROD || secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd ${{ github.event.inputs.environment }} && terraform init

      - name: Terraform Apply 
        run: cd ${{ github.event.inputs.environment }} && terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"