name:  My First Terraform Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
